---
page_title:
  title: Výstrahy a upozornění
  content: Výstrahy a upozornění jsou e-maily automaticky zasílané zaměstnancům, pakliže nastane nějaká událost na požadavku.
ticket_alert:
  title: Upozornění na nový požadavek
  content: '<p>Upozornění zaslané zaměstnancům při vytvoření nového požadavku.</p><p class="info-banner"><i class="icon-info-sign"></i> Toto upozornění není zasláno v případě automatického přiřazení požadavku prostřednictvím filtru požadavků nebo tématu podpory.</p>'
  links:
    - 
      title: Výchozí šablona upozornění na nový požadavek
      href: /scp/templates.php?default_for=ticket.alert
message_alert:
  title: Upozornění na novou zprávu
  content: Upozornění zaslané zaměstnanci, když přijde od zákazníka nová zpráva, která je přidaná k již existujícímu požadavku.
  links:
    - 
      title: Výchozí šablona upozornení na novou zprávu
      href: /scp/templates.php?default_for=message.alert
internal_note_alert:
  title: Oznámení o nové aktivitě
  content: Upozoronění zaslané zaměstnancům, pokud na požadavku vznikla nová událost, jako je např. přidání nové interní poznámky či odpověďi zaměstnance k danému požadavku.
  links:
    - 
      title: Výchozí šablona upozornení na aktivitu
      href: /scp/templates.php?default_for=note.alert
assignment_alert:
  title: Upozoronění o přiřazení požadavku
  content: Upozornění zaslané zaměstnanci při přiřazení požadavku.
  links:
    - 
      title: Výchozí šablona upozornení o přiřazení požadavku
      href: /scp/templates.php?default_for=assigned.alert
transfer_alert:
  title: Upozornění o předání požadavku
  content: Upozornění zaslané zaměstnancům, pokud je požadavek předán mezi odděleními.
  links:
    - 
      title: Výchozí šablona pro upozornění o předání požadavku
      href: /scp/templates.php?default_for=transfer.alert
overdue_alert:
  title: Upozornění na zpožděný požadavek
  content: Upozornění zaslané zaměstnancům, pokud nesplní lhůtu vyřešení, zadnou ručně nebo na základě SLA.
  links:
    - 
      title: Výchozí šablona pro upozornění na zastaralého požadavku
      href: /scp/templates.php?default_for=ticket.overdue
    - 
      title: Nastavení plánů SLA
      href: /scp/slas.php
system_alerts:
  title: Systemové upozornění
  content: 'Důležité systémové události jsou odeslané správci (%{config.admin_email}). V závislosti na nastavení <span class="doc-desc-title">úrovně logu</span>, jsou události takté zaznamenány v <span class="doc-desc-title">systémém logu</span>.'
  links:
    - 
      title: Zobrazit systémové logy
      href: /scp/logs.php
    - 
      title: Změna e-mailové adresy správce
      href: /scp/settings.php?t=emails
