---
knowledge_base_settings:
  title: Nastavení báze znalostí
  content: ""
knowledge_base_status:
  title: Stav báze znalostí
  content: 'Tato volba umožní vašim zákazníkům samoobslužný přístup k článkům vaší veřejné báze znalostí.<br><br>Kategorie báze znalostí a častých dotazů mohou označeny jako interní (viditelné pouze pro zaměstnance).
  links:
    - 
      title: Správa báze znalostí
      href: /scp/kb.php
restrict_kb:
  title: Omezení přístupu do báze znalostí
  content: Znemožní neregistrovaným uživatelům přistupovat do báze znalostí na zákaznickém portále.
  links:
    - 
      title: Nastavení přístupových práv
      href: /scp/settings.php?t=access
canned_responses:
  title: Předpřipravené odpovědi
  content: 'Tato volba umožní zaměstnancům použití <span class="doc-desc-title">předpřipravených odpovědí</span> při odpovídání na požadavky.'
  links:
    - 
      title: Správa předpřipravených odpovědí
      href: /scp/canned.php
