---
new_ticket:
  title: Nový požadavek
  content: Povolte tuto možnost, pokud chcete odeslat automatickou odpověď zákazníkovi při zadání nového požadavku.
  links:
    - 
      title: Šablona automatické odpovědi při zadání nového požadavku
      href: /scp/templates.php?default_for=ticket.autoresp
new_ticket_by_staff:
  title: Nový požadavek vytvořený zaměstnancem
  content: 'Oznámení odeslané v případě, že zaměstnanec vytvoří požadavek za zákazníka. <em>Agent toto nastavení může při zakládání požadavku přepsat.</em>'
  links:
    - 
      title: Šablona upozornění na nový požadavek
      href: /scp/templates.php?default_for=ticket.notice
new_message_for_submitter:
  title: Potvrzení nové zprávy
  content: 'Oznémení odeslané v případě, že je k existujícímu zákaznickému požadavku přidána nová zpráva.'
  links:
    - 
      title: Šablona potvrzení nové zprávy
      href: /scp/templates.php?default_for=message.autoresp
new_message_for_participants:
  title: Upozornění na novou zprávu
  content: Rozešle uporoznění na novou zprávu přijatou od jejího odesílatele všem ostatním účastníkum požadavku.
  links:
    - 
      title: Šablona pro zprávu o nové aktivitě
      href: /scp/templates.php?default_for=ticket.activity.notice
overlimit_notice:
  title: Oznámení o překročení limitu
  content: 'Oznámení zaslané zákazníkovi při odmítnutí požadavku z důvodu  překročení<span class="doc-desc-title">maximálního počtu otevřených požadavků</span>.'
  links:
    - 
      title: Šablona upozornění na překročení limitu
      href: /scp/templates.php?default_for=ticket.overlimit
    - 
      title: '<em>Max. počet otevřených požadavků</em>'
      href: /scp/settings?t=tickets
