---
company_information:
  title: Informace o společnosti
  content: Toto se vztahuje na firmu či organizaci provozující tento osTicket systém a její zaměstnance podpory. Zde uvedené informace se objeví v podpisech (např. v patičkách) odesílaných e-mailů s odpověďmi zaměstnanců.
  links:
    - 
      title: Základní informace o firmě/organizaci
      href: /scp/forms.php?type=C
landing_page:
  title: Úvodní stránka
  content: '<span class="doc-desc-title">Úvodní stránka</span> se zobrazí na hlavní stránce vašeho zákaznického portálu.'
offline_page:
  title: Offline stránka
  content: '<span class="doc-desc-title">Offline stránka</span> se zobrazí místo úvodní stránky zákaznického portálu, pokud je systém zákaznické podpory ve stavu off-line, viz Správcovsky panel -&gt; Nastavení -&gt; Systém -&gt; Stav systému zákaznické podpory.'
default_thank_you_page:
  title: Výchozí stránka s poděkováním
  content: '<span class="doc-desc-title">Stránka s poděkováním</span> se zobrazí zákazníkovi po tom, co <span class="doc-desc-title">zákazník</span> založí nový požadavek.<br/><br/><span class="doc-desc-title">Stránka s poděkováním</span> může být různá pro každé téma podpory.'
logos:
  title: Loga
  content: 'Zde si zvolte <span class="doc-desc-title">logo</span>, které se bude zobrazovat zákazníkům na zákaznickém portálu.'
upload_a_new_logo:
  title: Nahrát nové logo
  content: 'Vyberte obrázek ve formátu .gif, .jpg nebo .png. Jeho rozměry budou přizpůsobeny, poměr stran bude zachován. Nicméně datová velikost obrázku nebude redukována a proto pro rychlé načítání stránek doporučujeme, aby rozměry výrazně nepřesahovaly výchozí velikost obrázku (817px &times; 170px).'
