---
helpdesk_status:
  title: Stav systému zákaznické podpory
  content: 'Pokud změníte stav na <span class = "doc-desc-opt">Off-line</ span>, zákaznické rozhraní bude zakázáno. Nemá však vliv na běžnou činnost panelu zaměstnance.'
helpdesk_url:
  title: URL systému zákaznické podpory
  content: Tento URL odkaz je základní pro instalaci systému. Používá se v e-mailové komunikaci pro směrování uživatelů zpět na systém zákaznické podpory.
helpdesk_name_title:
  title: Název systému zákaznické podpory
  content: Název systému, který bude zobrazován v kartě prohlížeče. Pokud bude váš systém zákaznické podpory uložen do záložek, tento název se bude zobrazovat jako jméno webu.
default_department:
  title: Výchozí oddělení
  content: 'Vyberte výchozí <span class="doc-desc-title">oddělení</span> pro požadavky, které nejsou automaticky směrovány na oddělení.<br/><br/>Požadavky mohou být směrovány podle nastavení tématu podpory, příchozího e-mailu a filtru požadavků.'
default_page_size:
  title: Výchozí počet záznamů na stránce
  content: 'Zvolte počet záznamů zobrazených na stránce ve frontách požadavků na panelu zaměstnance. Každý zaměstnanec si může tento počet nastavit na stránce <span class="doc-desc-title">uživatelských předvoleb</span>.'
default_log_level:
  title: Výchozí úroveň logu
  content: 'Určuje nejnižší úroveň problémů, které budou zaznamenávány do <span class="doc-desc-title">systémového logu</span>. <span class="doc-desc-opt">Debug</span> znamená nejnižší závažnost a <span class="doc-desc-opt">Error</span> znamená nejvyšší. Pokud například chcete vidět všechny problémy v <span class="doc-desc-title">systémovém logu</span>, zvolte <span class="doc-desc-opt">Debug</span>.'
purge_logs:
  title: Mazání logu
  content: 'Určuje dobu, po kterou budou uchovávány <span class="doc-desc-title">systémové logy</span>, než budou smazány.'
default_name_formatting:
  title: Výchozí formát jména
  content: Zvolte formát pro zobrazení jmen v systému. E-mailové šablony budou používat tento formát, pokud není specifikován jiný formát při použití proměnné.
  links:
    - 
      title: Podporované proměnné v šablonách e-mailů
      href: http://osticket.com/wiki/Email_templates
date_time_options:
  title: Možnosti data a času
  content: Následující nastavení definuje zobrazení data a času zákazníkům. Můžete je změnit pomocí formátovacích znaků PHP. Níze zobrazená data ukazují, jak bude výsledný formát vypadat.
  links:
    - 
      title: Formátovacích znaky data v PHP
      href: http://www.php.net/manual/en/function.date.php
