---
number_format:
  title: Formát čísla požadavku
  content: 'Nastavuje generování čísel požadavků. Použijte znak mřížky (`#`) na místě číslic. Jakýkoli jiný text ve formátovacím řetězci zůstane zachován. <span class="doc-desc-title">Témata podpory</span> mohou definovat vlastní číslování.<br/><br/>Například pro šestimístná čísla použijte <code>######</code>.'
sequence_id:
  title: Číselná řada požadavků
  content: 'Zvolte číselnou řadu pro určení číslování požadavků. Ve výchozím stavu jsou v systému inkrementální a náhodné číselné řady. Počet číselných řad není omezen. Můžete použít různé číselné řady ve <span class="doc-desc-title">formátu čísla požadavku</span> v nastavení témat požadavků.'
default_ticket_status:
  title: Výchozí stav pro nové požadavky
  content: Zvolte výchozí stav pro nové požadavky. Může být definován zvlášť pro každé téma podpory. Též může být přepsán filtrem požadavků.
  links:
    - 
      title: Spravovat stavy požadavků
      href: /scp/lists.php?type=ticket-status
default_sla:
  title: Výchozí plán SLA
  content: Zvolte výchozí plán SLA určující lhůtu, jak dlouho zůstane požadavek otevřen, než bude označen jako zpožděný.
  links:
    - 
      title: Správa plánů SLA
      href: /scp/slas.php
default_priority:
  title: Výchozí priorita
  content: 'Zvolte výchozí <span class="doc-desc-title">prioritu</span> pro požadavky bez automaticky nastavené priority.<br/><br/>Priorita může být přiřazena dle tématu podpory, cílového oddělení nebo nastavením filtru požadavků.'
maximum_open_tickets:
  title: Maximální počet otevřených požadavků
  content: 'Zadejte maximální <em>počet</em> požadavků, které může zákazník mít mít současně <strong>otevřen</strong>.<br><br>Zadejte <span class="doc-desc-opt">0</span>, pokud nechcete počet omezovat.'
agent_collision_avoidance:
  title: Doba zamčení požadavků
  content: |
    Zadejte maximální dobu, po kterou může zaměstnanec mít uzamčen požadavek bez jakékoliv aktivity.
    <br><br>Vložte<span class="doc-desc-opt">0</span>, pokud nechcete požadavky uzamykat.
email_ticket_priority:
  title: Priorita požadavků zaslaných e-mailem
  content: Použití priority z příznaku doručeného e-mailu
show_related_tickets:
  title: Zobrazit související požadavky
  content: 'Zobrazení všech souvisejících požadavků při přihlášení uživatele - jinak je přístup omezen pouze na jeden požadavek na jedno přihlášení'
human_verification:
  title: Ověření člověka
  content: 'Zapnutí CAPTCHA v zákaznickém portálu pro ověření, zda-li je požadavek zadáván lidskou osobou.<br><br>Vyžaduje GDLib knihovnu'
claim_tickets:
  title: Při odpovědi si přiřadit požadavek
  content: 'Volba pro automatické přiřazení nepřiřazených požadavků zaměstnanci, který na ně odpověděl.<br><br>Znovuotevřené požadavky jsou vždy přiřazeny tomu, kdo naposledy odpověděl.'
assigned_tickets:
  title: Přiřazené požadavky
  content: 'Volba pro vyloučení přiřazených požadavků ze <span class="doc-desc-title">seznamu otevřených požadavků</span>.'
answered_tickets:
  title: Zodpovězené požadavky
  content: 'Volba pro zobrazení zodpovězených požadavků v <span class="doc-desc-title">seznamu zodpovězených požadavků</span>. Jinak budou tyto požadavky zahrnuty v <span class="doc-desc-title">seznamu otevřených požadavků</span>.'
staff_identity_masking:
  title: Skrytí identity zaměstnance
  content: Volba pro skrytí jména zaměstnance během komunikace.
enable_html_ticket_thread:
  title: Povolit formátovaný text pro vlákno požadavku
  content: Volba pro použití formátovaného textu v komunikaci mezi agentem a klienty.
ticket_attachment_settings:
  title: Nastavení příloh požadavků
  content: 'Definuje nastavení pro přílohy vkládané do pole <span class="doc-desc-title">podrobnosti o problému</span>. Tato nastavení jsou použita pro všechny nové požadavky a zprávy nezávisle na jejich zdroji (zákaznický portál, e-mail, API atd.).'
max_file_size:
  title: Maximální velikost souboru
  content: Vyberte maximální velikost přílohy vložené zaměstnancem. Zahrnuje předpřipravené odpovědi, články báze znalostí a přílohy v odpovědích na požadavky.
ticket_response_files:
  title: Přílohy v odpovědi na požadavek
  content: Volba pro přiložení všech příloh vložené zaměstnancem v odpovědi na požadavek do e-mailu zaslanému zákazníkovi.
