---
agent_name_format:
  title: Styl zobrazení jména zaměstnance
  content: Vyberte styl zobrazení jmen zaměstnanců pro celý systém. Šablony e-mailů toto nastavení použijí, pokud není specifikován jiný formát.
staff_identity_masking:
  title: Skrytí identity zaměstnance
  content: Tato volba skryje jméno zaměstnance pro zákazníka během celé komunikace.
password_reset:
  title: Zásady pro vypršení platnosti hesla
  content: 'Nastavuje, jak často (v měsících) budou zaměstnanci povinni změnit své heslo. Pokud je toto vypnuto (nastaveno "Bez časového omezení"), tak hesla nikdy nevyprší.'
password_expiration_policy:
  title: Zásady pro vypršení platnosti hesla
  content: 'Nastavte, jak často budou zaměstnanci povinni změnit své heslo. Pokud je nastaveno na <span class="doc-desc-opt">Bez časového omezení</span>), tak hesla nikdy nevyprší.'
allow_password_resets:
  title: Povolit obnovu hesla
  content: 'Tato volba povolí zobrazení odkazu <span class="doc-desc-title">Obnova zapomenutého hesla</span> na <span class="doc-desc-title">přihlašovací stránce zaměstnanců</span> po tom, co selže přihlášení.'
reset_token_expiration:
  title: Lhůta obnovy hesla
  content: 'Vyberte délku (v minutách), jak dlouho bude <span class="doc-desc-title">odkaz na obnovu hesla</span> funkční. Když zaměstnanec požádá o <span class="doc-desc-title">obnovu hesla</span>, je jim zaslán e-mail s odkazem, který jim umožní změnu hesla provést.'
staff_session_timeout:
  title: Maximální doba nečinnosti zaměstnance
  content: 'Vyberte maximální délku (v minutách) nečinnosti zaměstnance, než bude vyžadováno, aby se zaměstnanec znovu přihlásil.<br><br>Pokud chcete <span class="doc-desc-title">maximální dobu nečinnosti zaměstnance</span> vypnout, zadejte 0.'
bind_staff_session_to_ip:
  title: Spárovat zaměstnance s IP adresou
  content: 'Tato volba zajistí, aby přihlášení zaměstnance bylo spárováno s IP adresou.<br><br>Toto nastavení není doporučováno pro uživatele s dynamicky přidělovanými IP adresami.'
