---
number_format:
  title: Formát čísla úkolů
  content: 'Toto nastavení je použito při generování čísel úkolů. Použijte znak mřížky (`#`) v místě, kam chcete umístit číslice. Jakékoliv jiné znaky budou zachovány.<br/><br/>Například, pro šestičíselný formát použijte <code>######</code>.'
sequence_id:
  title: Číselná řada úkolů
  content: Vyberte číselnou řadu úkolů, ze které se budou odvozovat nová čísla úkolů. Systém má zvyšující se číselnou řadu a náhodnou číselnou řadu. Můžete vytvořit tolik číselných řad, kolik potřebujete.
default_sla:
  title: Výchozí plán SLA
  content: Vyberte výchozí plán SLA (Service Level Agreement) pro určení, jak dlouho může zůstat úkol otevřený, než bude označen za zpožděný.
  links:
    - 
      title: Správa plánů SLA
      href: /scp/slas.php
default_priority:
  title: Výchozí priorita
  content: 'Vyberte výchozí <span class="doc-desc-title">prioritu</span> pro úkoly, jimž není priorita určena automaticky.'
task_attachment_settings:
  title: Přílohy vláken úkolů
  content: 'Proveďte nastavení souboru připojených k položce <span class="doc-desc-title">popis</span>. Toto nastavení je použito pro všechny nové úkoly a nové zprávy nezávisle na zdroji (zákaznický portál, e-mail, API apod.).'
page_title:
  title: Výstrahy a upozornění
  content: Výstrahy a upozornění jsou automatické e-mailové zaslané zaměstnancům v případě, že nastane nějaká událost na úkolu.
task_alert:
  title: Upozornění na nový úkol
  content: '<p>Upozornění je zasláno zaměstnancům, když je vytvořen nový úkol.</p><p class="info-banner"> <i class="icon-info-sign"></i> Toto oznámení není odesláno v případě, že je úkol automaticky přiřazen.</p>'
  links:
    - 
      title: Výchozí šablona upozornění na nový úkol
      href: /scp/templates.php?default_for=task.alert
activity_alert:
  title: Upozornění na novou událost
  content: Upozornění je zasláno zaměstnancům, když je k existujímu úkolu přidána nějaká nová zpráva.
  links:
    - 
      title: Výchozí šablona upozornění na novou aktivity
      href: /scp/templates.php?default_for=task.activity.alert
assignment_alert:
  title: Upozorněnní na přiřazení úkolu
  content: Upozronění odeslané zaměstnancům v případě přiřazení úkolu.
  links:
    - 
      title: Výchozí šablona o přiřazení úkolu
      href: /scp/templates.php?default_for=task.assignment.alert
transfer_alert:
  title: Task Transfer Alert
  content: Upozornění odeslané zaměstnancům v případě předání úkolu mezi odděleními.
  links:
    - 
      title: Výchozí šablona upozornění o předání úkolu
      href: /scp/templates.php?default_for=task.transfer.alert
overdue_alert:
  title: Upozornění na zpožděný úkol
  content: Upozornění zaslané zaměstnancům v momentě, kdy úkol se na základě plánu SLA či nastavení termínu stane zpožděný.
  links:
    - 
      title: Výchozí šablona upozornění na zastaralý úkol
      href: /scp/templates.php?default_for=task.overdue.alert
    - 
      title: Správa plánů SLA
      href: /scp/slas.php
